import {chromium} from 'playwright';
import fs from 'node:fs';import crypto from 'node:crypto';
const sourceHashes=()=>Object.fromEntries(['app/page.tsx','app/globals.css'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync('src/'+p)).digest('hex')]));const sourceHashesStart=sourceHashes();
const phase=process.env.QA_PHASE||'after',quick=process.env.QA_QUICK==='1';
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});const rows=[];
try{
const cases=(quick?[360]:[320,360,390,412]).flatMap(width=>(quick?['zh-CN']:['en','zh-CN']).flatMap(locale=>(quick?[2]:[1,1.5,2]).flatMap(scale=>(quick?['over']:['over','paused']).map(mode=>({width,locale,scale,mode,numbers:'high'})))));
if(phase==='after')for(const locale of ['en','zh-CN']){
 cases.push({width:320,locale,scale:2,mode:'over',numbers:'max'});
 for(const mode of ['over','paused']){cases.push({width:320,height:568,locale,scale:2,mode,numbers:'high'});for(const scale of [1,2])cases.push({width:1280,height:720,locale,scale,mode,numbers:'high'});}
}
for(const {width,height=740,locale,scale,mode,numbers} of cases.filter(c=>process.env.QA_FOCUSED!=='1'||(c.width<750&&(c.mode==='over'||(c.scale===2&&c.width===320))))){
 const context=await browser.newContext({viewport:{width,height},locale,isMobile:width<750,hasTouch:width<750,deviceScaleFactor:1});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));const violations=[];
 try{
  await page.goto(`http://127.0.0.1:3028/?lang=${locale}&mode=${mode}&numbers=${numbers}`);await page.locator('.result-panel').waitFor();await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(scale=>{const elements=[...document.body.querySelectorAll('*')];const values=elements.map(el=>{const c=getComputedStyle(el);return[el,parseFloat(c.fontSize),c.lineHeight]});for(const[el,font,line]of values){el.style.setProperty('font-size',`${font*scale}px`,'important');if(line!=='normal')el.style.setProperty('line-height',`${parseFloat(line)*scale}px`,'important');}window.__androidQA.scale=scale;},scale);await page.waitForTimeout(100);
  const measures=await page.evaluate(()=>{
   const bounds=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};};
   const textBounds=el=>{const range=document.createRange();range.selectNodeContents(el);return [...range.getClientRects()].map(r=>({x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}));};
   const panel=document.querySelector('.result-panel'),overlay=panel.parentElement,arena=document.querySelector('.arena');
   return{viewport:{width:innerWidth,height:innerHeight},panel:bounds(panel),arena:bounds(arena),overlay:{...bounds(overlay),scrollHeight:overlay.scrollHeight,clientHeight:overlay.clientHeight,overflowY:getComputedStyle(overlay).overflowY},document:{scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth},stats:[...document.querySelectorAll('.result-stats>div')].map(el=>({box:bounds(el),text:textBounds(el),textContent:el.textContent})),heading:{box:bounds(panel.querySelector('h2')),text:textBounds(panel.querySelector('h2'))}};
  });
  if(measures.document.scrollWidth>measures.document.clientWidth+1)violations.push('document horizontal overflow');
  for(const [i,stat] of measures.stats.entries())if(stat.box.x<measures.panel.x-1||stat.box.right>measures.panel.right+1)violations.push(`stat ${i} horizontally clipped by result panel`);
  for(let i=0;i<measures.stats.length;i++){const stat=measures.stats[i];for(const r of stat.text)if(r.width>0&&(r.x<stat.box.x-1||r.right>stat.box.right+1))violations.push(`stat ${i} text outside its column`);for(let j=i+1;j<measures.stats.length;j++)for(const a of stat.text)for(const b of measures.stats[j].text)if(Math.min(a.right,b.right)-Math.max(a.x,b.x)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)>1)violations.push(`stat ${i}/${j} overlap`);}
  const header=await page.evaluate(()=>{const rect=r=>({x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height});return [...document.querySelectorAll('.topbar button')].map(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),glyphs=[];while(walker.nextNode()){const range=document.createRange();range.selectNodeContents(walker.currentNode);for(const r of range.getClientRects())if(r.width>0&&r.height>0)glyphs.push(rect(r));}return {text:el.textContent.trim(),box:rect(el.getBoundingClientRect()),glyphs};});});
  if(width<750)for(const button of header){const b=button.box;if(!b.width||!b.height)continue;if(b.width<43.9||b.height<43.9)violations.push(`header touch target too small: ${button.text}`);if(b.x<0||b.right>width+1)violations.push(`header button outside viewport: ${button.text}`);for(const r of button.glyphs)if(r.x<b.x-1||r.right>b.right+1||r.y<b.y-1||r.bottom>b.bottom+1)violations.push(`header text clipped: ${button.text}`);}
  const keyboard={};if(phase==='after'){await page.bringToFront();await page.locator('.result-panel').focus();await page.locator('.result-panel').evaluate(el=>el.scrollTo({top:0,behavior:'instant'}));keyboard.before=await page.locator('.result-panel').evaluate(el=>el.scrollTop);keyboard.focused=await page.locator('.result-panel').evaluate(el=>document.activeElement===el);const scrollable=await page.locator('.result-panel').evaluate(el=>el.scrollHeight>el.clientHeight+5);await page.keyboard.press('Space');if(scrollable)await page.waitForFunction(()=>document.querySelector('.result-panel').scrollTop>0,{},{timeout:1000}).catch(()=>{});keyboard.after=await page.locator('.result-panel').evaluate(el=>el.scrollTop);keyboard.mode=await page.evaluate(()=>window.__androidQA.live.mode);if(keyboard.mode!==mode)violations.push('Space on focused result panel changes gameplay');if(!keyboard.focused)violations.push('result panel cannot receive keyboard focus');if(scrollable&&keyboard.after<=keyboard.before)violations.push('focused result panel does not scroll with Space');}
  const actions=[];for(const b of await page.locator('.result-panel button').all()){
   await b.scrollIntoViewIfNeeded();const action=await b.evaluate(el=>{const r=el.getBoundingClientRect();let clip={left:0,top:0,right:innerWidth,bottom:innerHeight};for(let p=el.parentElement;p;p=p.parentElement){const c=getComputedStyle(p);if(/hidden|clip|auto|scroll/.test(c.overflowY+' '+c.overflowX)){const a=p.getBoundingClientRect();clip={left:Math.max(clip.left,a.left),top:Math.max(clip.top,a.top),right:Math.min(clip.right,a.right),bottom:Math.min(clip.bottom,a.bottom)};}}const c=getComputedStyle(el);return{text:el.textContent.trim(),x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom,clip,visible:getComputedStyle(el).display!=='none'&&r.width>0,target:getComputedStyle(el).pointerEvents};});if(!action.visible)continue;actions.push(action);if(action.width<43.9||action.height<43.9)violations.push(`touch target too small: ${action.text}`);if(action.x<action.clip.left-1||action.right>action.clip.right+1||action.y<action.clip.top-1||action.bottom>action.clip.bottom+1)violations.push(`action clipped after scrolling: ${action.text}`);
  }
  // The first content is reachable as well as the final action: center alignment can otherwise strand the top above an overflow region.
  await page.locator('.result-panel>.eyebrow').scrollIntoViewIfNeeded();const start=await page.locator('.result-panel>.eyebrow').boundingBox();const arena=await page.locator('.arena').boundingBox();if(start.y<Math.max(0,arena.y)-1)violations.push('result beginning unreachable');
  if(((width===320||width===360)&&scale===2)||(width===320&&(scale===1.5||height===568))||(width===1280&&scale===2))await page.screenshot({path:`work/android-large-text-qa/${phase}-${width}x${height}-${locale}-${scale}-${mode}-${numbers}.png`});
  rows.push({width,height,locale,scale,mode,numbers,keyboard,header,passed:violations.length===0&&errors.length===0,violations:[...new Set(violations)],measures,actions,errors});
 }catch(e){rows.push({width,height,locale,scale,mode,numbers,passed:false,error:String(e),errors});}
 console.log(JSON.stringify({width,locale,scale,mode,...rows.at(-1),measures:undefined,actions:undefined}));await context.close();
}
}finally{fs.writeFileSync(`work/android-large-text-qa/${phase}-results.json`,JSON.stringify({phase,selection:process.env.QA_FOCUSED==='1'?'mobile heading affected cases':'full matrix',sourceHashesStart,sourceHashesEnd:sourceHashes(),method:'Snapshot computed font sizes and line heights then multiply in px; viewport/layout width unchanged. Isolated production Home with synthetic in-memory final/paused state only.',rows},null,2));await browser.close();}
if(phase==='after'&&rows.some(r=>!r.passed))process.exitCode=1;
